apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  namespace: flink
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"
spec:
  clusterIP: None
  ports:
  - name: prom
    port: 9999
  selector:
    app: flink
    component: taskmanager
  type: ClusterIP
  sessionAffinity: None
